# Generated by Django 5.1.2 on 2024-10-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_model_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='lastname',
        ),
    ]
