# Generated by Django 5.1.2 on 2024-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_model_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
